### ISSUE TITLE
error called LLwF_LLN function

### ISSUE THREAD

**Issue by Alro10** [tony-ko/LLEF#1]
Hello!

When I tried to run LLwF_RK2, I found this error:

error: 'LLwF_LLN' undefined near line 143 column 29

Can you add this file? Please.

Thanks in advance.

**Comment by yumtong** [comment]
Hi~ I think 'LLwF_LLN' is just a piece of code about the Rk calculations.  
[4RK.txt](https://github.com/tony-ko/LLEF/files/3631985/4RK.txt)

**Comment by tony-ko** [comment]
Just have noticed that I had some issues with the project.

I forgot to include the function defining the r.h.s. of the LLE. It was fixed three years ago.
